version: '3.7'

services:

  core:
    build:
      context: core
    env_file:
      - .env
    restart: always
    depends_on:
      - minio


  minio:
    image: 'minio/minio'
    hostname: minio
    ports:
    - "9000:9000"
    volumes:
    - minio:/data
    restart: always
    env_file:
      - .env
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio: